# models/walmart_dim_fact/schema.yml
version: 2
models:
  - name: walmart_date_dim
    columns:
      - name: store_id 
        tests:
          - not_null
      - name: date_id
        tests:
          - not_null
          - unique
      - name: insert_date
      - name: update_date
